name: fe_lam
description: "FE Learning Management System by SCA"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  webview_flutter: ^4.10.0
  url_launcher: ^6.1.11
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  khmer_date: ^1.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  toastification: ^2.3.0
  material_theme_builder: ^1.0.4
  loader_overlay: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fe-logo.png
    - assets/images/rupp-logo.png
    - assets/images/sca-logo.png